### ISSUE TITLE
Check activity supported at top of API functions

### ISSUE THREAD

**Issue by danmarsden** [plagiarism/moodle-plagiarism_plagiarisma#1]
A cursory look at your code suggests that you only support the mod_assign activity but the core API supports forum and workshop activities and some other organisations have their own activities that implement the plagiarism API.

You should be checking the activity type at the top of a number of functions before you make any db calls to ensure that you are not calling your code in places where it is not supported.

**Comment by plagiarism** [comment]
I've fixed all things.
