### ISSUE TITLE
plugin doesn't set config var to enable plugin.

### ISSUE THREAD

**Issue by danmarsden** [plagiarism/moodle-plagiarism_plagiarisma#5]
The Plagiarism API relies on the plugin setting a global config var to determine if it is enabled or not using code like this:
(get_config('plagiarism', $plugin."_use")

The plagiarisma plugin isn't saving this var and is using the following for all it's config on settings.php

set_config($field, $value, 'plagiarism_plagiarisma');

That is good to use for general settings (account details etc) but unfortunately it requires you to store the plagiarisma_use setting within the 'plagiarism' config var like this:
set_config('plagiarisma_use', $value, 'plagiarism');

Using the current code I cannot enable the plugin due to this issue.

**Comment by plagiarism** [comment]
added.
