### ISSUE TITLE
php errors

### ISSUE THREAD

**Issue by danmarsden** [plagiarism/moodle-plagiarism_plagiarisma#7]
You need to add global $DB to the top of the function.

Notice: Undefined variable: DB in /home/dan/www/moodle-r2/plagiarism/plagiarisma/lib.php on line 419

Fatal error: Call to a member function get_records_menu() on a non-object in /home/dan/www/moodle-r2/plagiarism/plagiarisma/lib.php on line 419

**Comment by plagiarism** [comment]
added.
