### ISSUE TITLE
textlib.php licence

### ISSUE THREAD

**Issue by danmarsden** [plagiarism/moodle-plagiarism_plagiarisma#9]
it looks like you have copied some textlib functions from Alex Rembish and have added your own copyright statement and a licence (GPL v3) but the original code from Alex doesn't have any licence information - have you asked Alex if it's ok to licence under GPL 3?

**Comment by plagiarism** [comment]
sure, I asked him and he agreed.

**Comment by danmarsden** [comment]
great - I was going to ask you to document that but I think you have here by commenting and closing this issue :-)

**Comment by plagiarism** [comment]
oh, sorry for closing this issue ;) I can forward you our mailing, but it's in russian. Do you read russian language? Let me know.

**Comment by danmarsden** [comment]
No need - I was saying that your comment above is probably sufficient and I don't think you need to do anything else for this. Thanks!
